/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InboxView: typeof import('./src/components/tft/InboxView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TierColumn: typeof import('./src/components/tft/TierColumn.vue')['default']
  }
}
