/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompCard: typeof import('./src/components/tft/CompCard.vue')['default']
    CompEditDialog: typeof import('./src/components/tft/CompEditDialog.vue')['default']
    CompUploadDialog: typeof import('./src/components/tft/CompUploadDialog.vue')['default']
    InboxView: typeof import('./src/components/tft/InboxView.vue')['default']
    KeywordsInput: typeof import('./src/components/tft/KeywordsInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TierBoard: typeof import('./src/components/tft/TierBoard.vue')['default']
    TierColumn: typeof import('./src/components/tft/TierColumn.vue')['default']
  }
}
