services:
  db:
    image: postgres:16-alpine
    container_name: riot_hub_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    image: wshu7/riot-hub-backend:latest
    build: ./backend
    container_name: riot_hub_backend
    user: "${PUID:-0}:${PGID:-0}"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-0}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-}
    volumes:
      - ./data/static:/app/staticfiles
      - ./data/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: wshu7/riot-hub-frontend:latest
    build: ./frontend
    container_name: riot_hub_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./data/static:/var/www/static:ro
      - ./data/media:/var/www/media:ro
