# Generated by Django 5.2.10 on 2026-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0003_remove_teamcomposition_uniq_comp_code_per_season_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamcomposition',
            name='uniq_comp_code_per_season',
        ),
        migrations.AddConstraint(
            model_name='teamcomposition',
            constraint=models.UniqueConstraint(fields=('season', 'filename', 'comp_code'), name='uniq_comp_filename_code_per_season'),
        ),
    ]
