# Generated by Django 5.2.10 on 2026-07-08 13:22

import tft.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0004_remove_teamcomposition_uniq_comp_code_per_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=tft.models.season_background_upload_to),
        ),
    ]
