# Generated by Django 5.2.10 on 2026-02-04 09:08

import core.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=core.models.upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('comp_code', models.CharField(max_length=255)),
                ('tier_level', models.IntegerField()),
                ('tier_display', models.CharField(max_length=255)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'comp_code'), name='uniq_comp_code_per_season')],
            },
        ),
    ]
