# Generated by Django 5.2.10 on 2026-02-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcomposition',
            name='comp_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
