# Generated by Django 5.2.10 on 2026-02-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teamcomposition_comp_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamcomposition',
            name='uniq_comp_code_per_season',
        ),
        migrations.AddConstraint(
            model_name='teamcomposition',
            constraint=models.UniqueConstraint(fields=('filename', 'comp_code'), name='uniq_comp_code_per_season'),
        ),
    ]
